"""Generate platform-independent Dart fixtures from the committed JSON vectors."""
import json
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parents[1]
fixtures = {name: json.loads((root / 'test' / 'fixtures' / f'{name}.json').read_text())
            for name in ('rfc9964', 'webauthn', 'packed')}
text = json.dumps(fixtures, separators=(',', ':'))
(root / 'test' / 'fixtures' / 'fixtures.dart').write_text(
    '// Generated by tool/embed_fixtures.py. Do not edit.\n'
    "const fixtureJson = r'''" + text + "''';\n")
subprocess.run(['dart', 'format', str(root / 'test' / 'fixtures' / 'fixtures.dart')], check=True)
