"""Import RFC 9964's published examples, not signatures generated by this backend."""
import json
from pathlib import Path
import urllib.request
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
source = 'https://www.rfc-editor.org/rfc/rfc9964.xml'
document = ET.fromstring(urllib.request.urlopen(source).read())
vectors = []
for element in document.iter('artwork'):
    if 'raw_public_key' not in (element.text or ''):
        continue
    # RFC artwork wraps JSON strings onto physical lines for publication.
    obj = json.loads(element.text.replace('\n', ''))
    key = bytes.fromhex(obj['raw_public_key'])
    level = {1312: 44, 1952: 65, 2592: 87}[len(key)]
    vectors.append(dict(source=source + '#' + element.attrib['pn'],
                        algorithm=f'ml-dsa-{level}', key=list(key),
                        message=list(bytes.fromhex(obj['raw_to_be_signed'])),
                        signature=list(bytes.fromhex(obj['raw_signature']))))
assert len(vectors) == 6
out = root / 'test' / 'fixtures'
out.mkdir(exist_ok=True)
(out / 'rfc9964.json').write_text(json.dumps(vectors, separators=(',', ':')) + '\n')
